### ISSUE TITLE
Running sakis3g on Bash on Ubuntu on Windows

### ISSUE THREAD

**Issue by adonese** [Trixarian/sakis3g-source#10]
Well in fact that might quite weird. Why would someone want to do that anyway?
While I was trying to use sakis on Bash on Ubuntu on Windows it failed to locate my usb modem. Any ideas how to solve this?

**Comment by Trixarian** [comment]
You're going to need more than just bash for it to work. Assuming you somehow got usb-modeswitch to work (unlikely considering the naming scheme is incompatible with Windows' one since it uses ":" in file names), you'd still need either wvdial or ppp to dial up with, and several gnu coreutils for it to even run. I barely got it to work with SliTaz - and that was a Linux distro, all be it a micro-Linux. It required some clever packaging of the required coreutils which were missing.

**Comment by Trixarian** [comment]
Oh wait - you meant you're running Ubuntu in a virtual environment within Windows? I thought you meant you were running Bash with Windows (considering Microsoft is now adding bash to Windows 10). In that case, as long as the virtual environment has access to your USB devices (check with lsusb), the required access to 'lock' them (which is a little unlikely with virtualization) and has the required parts installed (coreutils, usb-modeswitch, bash and libusb), it should work.

**Comment by adonese** [comment]
I'm running it on Bash on Windows. I guess  I've a lot to do! Thanks
